### ISSUE TITLE
[bug] object width information should not be displayed

### ISSUE THREAD

**Issue by gilbertohasnofb** [sebpiq/pd-fileutils#20]
The width of an object is written in a .pd file as `, f <n>`, where <n> is a number (note that only pd vanilla and l2ork can change the width of an object). Pd-extended, for instance, is programmed to ignore such (which is fairly easy, since no object name can contain a comma). The same should be applied to pd-fileutils: either ignore these information or make use of it for correct width, but do NOT display it such as below (see the last __[unpack s s]__ in the very bottom of the patch which contains an `, f 14`):

https://enzienaudio.com/a/dave?fetch=http://forum.pdpatchrepo.info/uploads/files/upload-e60ec29d-d318-4a97-bd8b-d223650acc35.pd

Corect display: http://forum.pdpatchrepo.info/uploads/files/upload-cf44d166-49be-4ef4-9adb-dd90079f8d3b.png

**Comment by sebpiq** [comment]
This is now fixed, however rendering SVG doesn't yet handle custom object width see #10
