### ISSUE TITLE
semicolon and messages

### ISSUE THREAD

**Issue by gilbertohasnofb** [sebpiq/pd-fileutils#21]
When one types a semicolon inside a message in Pd, next time the patch is opened there is a line break between the semicolon and the rest of the message. Currently, pd-fileutils does not do that (see both messages in the right side of the patch below):

https://enzienaudio.com/a/dave?fetch=http://forum.pdpatchrepo.info/uploads/files/upload-e60ec29d-d318-4a97-bd8b-d223650acc35.pd

Corect display: http://forum.pdpatchrepo.info/uploads/files/upload-cf44d166-49be-4ef4-9adb-dd90079f8d3b.png

**Comment by sebpiq** [comment]
Closing as I don't want to reproduce all of Pd's strange quirks :)
