### ISSUE TITLE
[bug] comments are shown in different position than expected

### ISSUE THREAD

**Issue by gilbertohasnofb** [sebpiq/pd-fileutils#22]
For some reason, comments are being shown higher than expected. These can cause some conflicts, since comments are sometimes used to describe an object to its immediate side. E.g., look for the two comments `<- input 1, 2, 3 or 4 here` and `<- input a, b, c or d` in the following patch:

https://enzienaudio.com/a/dave?fetch=http://forum.pdpatchrepo.info/uploads/files/upload-e60ec29d-d318-4a97-bd8b-d223650acc35.pd

Corect display: http://forum.pdpatchrepo.info/uploads/files/upload-cf44d166-49be-4ef4-9adb-dd90079f8d3b.png

**Comment by sebpiq** [comment]
Fixed with c08f6cc70b21bf53dbec50ffb9ffce4faa8f3628
