### ISSUE TITLE
[enhancement] different thickness for signal cords

### ISSUE THREAD

**Issue by gilbertohasnofb** [sebpiq/pd-fileutils#23]
I would like to suggest making signal cords thicker (or rather message cords thinner), as with regular Pd, so that they can be easily identifiable. As of now, it's kind of tricky to see which patch cords are carrying signals and which aren't, e.g.: https://enzienaudio.com/a/dave?fetch=http://www.pdpatchrepo.info/hurleur/vfreeverb~alt.pd

**Comment by sebpiq** [comment]
the main problem is that this information is not contained in the patch
file. So I don't see how I could find it...

On Fri, Feb 6, 2015 at 3:25 PM, Gilberto Agostinho <notifications@github.com
> wrote:

> I would like to suggest making signal cords thicker (or rather message
> cords thinner), as with regular Pd, so that they can be easily
> identifiable. As of now, it's kind of tricky to see which patch cords are
> carrying signals and which aren't, e.g.:
> https://enzienaudio.com/a/dave?fetch=http://www.pdpatchrepo.info/hurleur/vfreeverb~alt.pd
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/pd-fileutils/issues/23>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by gilbertohasnofb** [comment]
Hmm, this is a bit tricky indeed, never thought of it from this perspective. With abstractions it would be easy, since you can know if it has an __[inlet]__ or __[inlet~]__, and an __[outlet]__ or __[outlet~]__, but for default objects I think you would need a list of them. And then you would have to deduce which type of cord is being used by using the information above together with the notation of cords in Pd's format: `#X connect object-ID outlet-ID object2-ID inlet-ID;`
If you'd like, I can ask in the mailling list how Pd handles the information about types of inlet/outlets for regular objects and extensions.

**Comment by mhroth** [comment]
@sebpiq you would need to encode the input and output type of each object type in your code (a huge dictionary I guess). That's they way I've always done it. After that you can follow @gilbertohasnofb's suggestion of looking at the inlet/outlet types.
